version: '2'

services:
  dpyproxy:
    ports:
      - "127.0.0.1:4433:4433"
      - "127.0.0.1:5533:5533"
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: ["--tls_frag_size", "20", "--debug", "--tls_port", "4433", "--tls_host", "0.0.0.0", "--dns_host", "0.0.0.0", "--dns_port", "5533"]